Display

<Display>
    BoxLayout:
        orientation: "vertical"
        GridLayout:
            rows: 3
            size_hint: 1,0.3
            Button:
                text: "Black and White"
            Button:
                text: "Inverse"
            Button:
                text: "Line Drawing"
            Button:
                text: "Pointilism"
            Button:
                text: "Sepia"
            Button:
                text: "Pixelate"
        Image:
            id: image
